# Generated by Django 4.2.3 on 2023-07-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('food_groups', models.CharField(max_length=255)),
                ('nutriscore', models.CharField(max_length=1)),
                ('allergens', models.TextField()),
                ('countries', models.CharField(max_length=255)),
                ('keywords', models.TextField()),
                ('ingredients_analysis_tags', models.TextField()),
            ],
        ),
    ]
