# Generated by Django 4.2.3 on 2023-07-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients_analysis_tags',
        ),
    ]
