# Generated by Django 4.2.3 on 2023-07-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_product_ingredients_analysis_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_analysis_tags',
            field=models.TextField(default=''),
        ),
    ]
